// The 143 static pages are generated by a factory, and nothing checked their links.
//
// Today they are clean — 0 dead hrefs, 0 dead srcs — which is the right moment to add this: it
// can only ever report a regression. A factory that emits one bad href produces a page that 404s
// for every visitor and every crawler, and the only way anyone finds out is by clicking it.
//
// It also pins the shape of the site graph, because that HAS gone wrong: the eight comparison
// pages and use-cases.html were a closed island, in no sitemap and linked from nothing that was
// (fixed in 27a57d4). An unlinked page is not a broken page, so this reports orphans against a
// named list rather than banning them.
//
// ABSOLUTE URLS ARE THE TRAP. The comparison pages link to the hub as
// "https://kishore2494.github.io/daily-pulse/use-cases.html", not as "use-cases.html". A link
// checker that only understands relative paths declares the hub an orphan and the absolute links
// external, which is exactly the wrong answer twice. It fooled my own first two passes at this.

import { readdirSync, existsSync, readFileSync } from "node:fs";

const SITE = "https://kishore2494.github.io/daily-pulse/";

// Pages that legitimately have no inbound link from another PAGE, each with a reason.
const ALLOWED_ORPHANS = new Map([
  ["tablet-frame.html", "a device mock-up used to compose store screenshots, not a page"],
  ["landing.html", "the marketing entry point; reached from search and the sitemap, not from another page"],
  ["sheets-setup.html", "linked from inside the app (app.js), which this file-level scan cannot see"],
  ["index.html", "the app itself — the root, so nothing links down to it"],
]);

const pages = readdirSync(".").filter((f) => f.endsWith(".html"));
const pageSet = new Set(pages);
const fail = [];

/** Resolve an href/src to a local path, understanding this site's absolute URLs. */
function local(raw) {
  let t = raw.split("#")[0].split("?")[0].trim();
  if (t.startsWith(SITE)) t = t.slice(SITE.length);
  else if (/^(https?:|mailto:|tel:|data:|\/\/)/i.test(t) || t === "") return null;
  t = t.replace(/^\.\//, "");
  if (t === "" || t === "/") return "index.html";
  return t;
}

const inbound = new Map(pages.map((p) => [p, 0]));
let checked = 0;

for (const f of pages) {
  const html = readFileSync(f, "utf8");
  for (const [attr, re] of [["href", /href="([^"]+)"/g], ["src", /src="([^"]+)"/g]]) {
    for (const m of html.matchAll(re)) {
      const t = local(m[1]);
      if (t === null) continue;
      checked++;
      if (!existsSync(t)) {
        fail.push(`${f}: dead ${attr} -> ${m[1]}`);
        continue;
      }
      if (attr === "href" && pageSet.has(t) && t !== f) inbound.set(t, inbound.get(t) + 1);
    }
  }
}

if (checked < 100) fail.push(`only ${checked} internal links found across ${pages.length} pages — this check has gone stale`);

const orphans = pages.filter((p) => inbound.get(p) === 0 && !ALLOWED_ORPHANS.has(p));
for (const p of orphans) {
  fail.push(`${p} has no inbound link from any page — it will not be crawled through the site, and nobody can reach it by clicking`);
}
// The reverse: an allow-listed orphan that is now linked has outgrown its excuse.
for (const [p, why] of ALLOWED_ORPHANS) {
  if (!pageSet.has(p)) fail.push(`ALLOWED_ORPHANS names ${p}, which no longer exists — the list is stale`);
  else if (inbound.get(p) > 0 && p !== "index.html") {
    console.log(`   note: ${p} is now linked from ${inbound.get(p)} page(s); the excuse "${why}" no longer applies`);
  }
}

if (fail.length) {
  console.error("\n\x1b[31m✗ link check failed:\x1b[0m");
  for (const f of fail.slice(0, 12)) console.error(`   ${f}`);
  if (fail.length > 12) console.error(`   … +${fail.length - 12} more`);
  console.error("");
  process.exit(1);
}
console.log(`links: ${checked} internal links across ${pages.length} pages, none dead, ${ALLOWED_ORPHANS.size - 1} page(s) unlinked by design`);
